name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Clean previous builds
      run: |
        cd android
        ./gradlew clean
    
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: budgetgoat-apk
        path: android/app/build/outputs/apk/release/app-release.apk
